[package]
name = "rittorrent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.137"
anyhow = "1.0.66"
url = "2.3.1"
format-bytes = "0.3.0"
